export const GET_VERSION = 'app/GET_VERSION';
export const GET_VERSION_SUCCESS = 'app/GET_VERSION_SUCCESS';
export const GET_VERSION_FAIL = 'app/GET_VERSION_FAIL';
export const CLEAN_DATA_BY_VERSION = 'app/CLEAN_DATA_BY_VERSION';
